name: sync
on:
  push:
    branches:
      - main
  schedule:
    - cron: "50 23 * * *" #sync only once at the end of the day
  workflow_dispatch:
env:
  ITS_IMDB_COOKIEATMAIN: ${{ secrets.IMDB_COOKIEATMAIN }}
  ITS_IMDB_COOKIEUBIDMAIN: ${{ secrets.IMDB_COOKIEUBIDMAIN }}
  ITS_IMDB_LISTS: ${{ secrets.IMDB_LISTS }}
  ITS_TRAKT_EMAIL: ${{ secrets.TRAKT_EMAIL }}
  ITS_TRAKT_PASSWORD: ${{ secrets.TRAKT_PASSWORD }}
  ITS_TRAKT_CLIENTID: ${{ secrets.TRAKT_CLIENTID }}
  ITS_TRAKT_CLIENTSECRET: ${{ secrets.TRAKT_CLIENTSECRET }}
  ITS_SYNC_SKIPHISTORY: ${{ secrets.SYNC_SKIPHISTORY }}
  ITS_SYNC_MODE: ${{ secrets.SYNC_MODE }}
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Build
        run: make build
      - name: Sync
        run: make sync
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
